### ISSUE TITLE
Error while loading tasks

### ISSUE THREAD

**Issue by Princesagga01** [ziziwho/clickbot#6]
The clickbot stops and displays an error message after completing not more than 15 tasks. ERROR:telethon.client.updates:Unhandled exception on join_start
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/telethon/client/updates.py", line 443, in _dispatch_update
    await callback(event)
  File "main.py", line 267, in join_start
    await client(JoinChannelRequest(channel_name))
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 166 seconds is required (caused by JoinChannelRequest)

**Comment by ziziwho** [comment]
Telegram detect your abusive requests, please wait for 166 seconds. It should work soon!

**Comment by RoffPal** [comment]
@ziziwho could they block my account because of this?
